language: python
python:
  - '3.6'
cache:
  pip: true
  directories:
    - /home/travis/.yarn-cache/
before_install:
  - nvm install 10
install: pip install pytest pytest-asyncio "jupyterlab~=2.0"
script:
  # Build the sdist (identical to what will be uploaded to eg pypi on release)
  - python setup.py sdist
  # Install the extension from the sdist ensuring the cache is unused
  - pip install jupyterlab_git[test] --pre --no-index --find-links=dist --no-deps --no-cache-dir -v
  # Install the extension dependencies based on the current setup.py
  - pip install jupyterlab_git[test]
  - jupyter labextension list
  - jupyter lab build
  - pytest jupyterlab_git -r ap
  - jlpm run test
  - python -m jupyterlab.browser_check
  - jlpm run lint
  - python tests/test-browser/run_browser_test.py
